<?php
declare(strict_types=1);

namespace a_Class;

// This is a class - just a code template
class Foo
{
    public function whoAmI()
    {
        echo sprintf('Hi, i\'m %s', self::class) . "\n";
    }
}

// This is object
$foo1 = new Foo();
$foo1->whoAmI();
echo 'Object hash: ' . spl_object_hash($foo1) . "\n\n";

$foo2 = new Foo();
$foo1->whoAmI();
echo 'Object hash: ' . spl_object_hash($foo2) . "\n";