<div class="case_studies bootstrap-block ">
    <main class="page-main">
        <div class="inner-box">
            <div class="main-body-content">
                <div class="menuBoard-header">
                    <h2 class="headingone">Vodafone</h2>
                    <div class="headingtwo text-center">Updating displays and terminals for mobile telecommunications
                        stores nationally
                    </div>
                </div>
            </div>
        </div>
    </main>
    <div class="fullWidthParallaxBanner">
        <div>
            <div class="casestudy-parallaxBanner ">
                <img src="<?= $block->getViewFileUrl('Geekhub_CmsExamples::images/vodafone/vodafone-mainbanner.jpg') ?>">
            </div>
            <div class="locationwrap ">
                <div class="page-main">
                    <div>
                        <div class="col-md-7 col-sm-5 clientdetail"><span>Client:</span> Mobile telecommunications giant
                            Vodafone
                        </div>
                        <div class="col-md-4 col-sm-5 clientdetail"><span>Location:</span> Australia</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="page-main">
        <div class="inner-box">
            <div class="casestudydesp">
                Vodafone is one of the world's leading mobile telecommunications companies, with a significant presence
                in Europe, the Middle East, Africa, Asia Pacific and the United States through the company's subsidiary
                undertakings, joint ventures, associated undertakings and investments. Vodafone has over 530 retail
                stores and approximately 5.4 million Vodafone customers spread across Australia.
            </div>

        </div>
    </div>

    <div class="page-main">
        <div class="inner-box">
            <div class="heading-challenge text-center">Challenge</div>
            <div>
                <div class="col-md-6 col-sm-6 col-xs-12 disTabCell">
                    <ul class="casestudypoints">
                        <li>Vodafone required a display mounting system which could organise its national store
                            terminals for high performance commercial services
                        </li>
                        <li>Needed excellent space management solutions for staff and customers</li>
                    </ul>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-12 disTabCell">
                    <ul class="casestudypoints">
                        <li>Wanted to create a better in-store customer experience by providing free internet access
                        </li>
                        <li>High-demand, public-facing environment required durable solutions</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Geekhub_CmsExamples/js/fullWidth": {
                "elementImg":
                    "fullWidthParallaxBanner"

            }
        }
    }
</script>