<?php /** @var \Magento\Catalog\Block\Product\View $block */ ?>
<?php $product = $block->getProduct();
    $imageObject = $block->getImage($product, 'product_base_image');
?>
<div class="catalog-product-view-tab-request-sample-form">
    <h2><?= $block->escapeHtml(__('Request a Sample Form')) ?></h2>
    <div>
        <?php if ($imageObject) : ?>
            <div class="image-wrapper">
                <?= $imageObject->toHtml() ?>
            </div>
        <?php endif; ?>
        <form class="form request-sample"
              action="<?= $block->escapeUrl($block->getUrl('request_sample/submit')) ?>"
              id="request-sample-form"
              method="post"
              data-mage-init='{"geekHubRequestSample":{}}'
              onsubmit="return false;"
        >
            <fieldset class="fieldset">
                <legend class="legend">
                    <span><?= $block->escapeHtml(__('Write Us')) ?></span>
                </legend>
                <br/>
                <div class="field note no-label">
                    <?= $block->escapeHtml(__('Please send information if you want to order sample product')) ?>
                </div>
                <div class="field name required">
                    <label class="label" for="name">
                        <span><?= $block->escapeHtml(__('Name')) ?></span>
                    </label>
                    <div class="control">
                        <input name="name"
                               id="name"
                               title="<?= $block->escapeHtmlAttr(__('Name')) ?>"
                               class="input-text" type="text"
                               data-validate="{required:true}"
                        />
                    </div>
                </div>
                <div class="field email required">
                    <label class="label" for="email">
                        <span><?= $block->escapeHtml(__('Email')) ?></span>
                    </label>
                    <div class="control">
                        <input name="email"
                               id="email"
                               title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                               class="input-text"
                               type="email"
                               data-validate="{required:true, 'validate-email':true}"
                        />
                    </div>
                </div>
                <div class="field phone">
                    <label class="label" for="phone">
                        <span><?= $block->escapeHtml(__('Phone Number')) ?></span>
                    </label>
                    <div class="control">
                        <input name="phone"
                               id="phone"
                               title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                               class="input-text"
                               type="text"
                        />
                    </div>
                </div>
                <div class="field comment required">
                    <label class="label" for="request">
                        <span><?= $block->escapeHtml(__('What’s on your mind?')) ?></span>
                    </label>
                    <div class="control">
                        <textarea name="request"
                                  id="request"
                                  title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>"
                                  class="input-text"
                                  cols="5" rows="3"
                                  data-validate="{required:true}"
                        ></textarea>
                    </div>
                </div>
            </fieldset>
            <input type="hidden" name="customer_id" value="<?php echo $block->getCurrentCustomerId(); ?>" />
            <div class="actions-toolbar">
                <div class="primary">
                    <input type="hidden" name="sku" value="<?= $block->escapeHtml($product->getSku()) ?>"/>
                    <input type="hidden" name="product_name" value="<?= $block->escapeHtml($product->getName()) ?>"/>
                    <input type="hidden" name="hideit" id="hideit" value=""/>
                    <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                        <span><?= $block->escapeHtml(__('Submit')) ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
<?= $block->getChildHtml('request.list') ?>