<?php
/** @var $block \Magento\Catalog\Block\Product\View */
?>
<div id="product-name"
     class="chapter-explanation"
     data-mage-init='{"geethubHello": {"message": "Hello GeekHub"}}'>

    <pre>
            {
                "*": {
                    "Geekhub_Lesson5/js/example":{}
                }
            }
    </pre>
    <span><?php echo $block->escapeHtml(__('Data-mage-init Attribute'))?></span>
</div>
<div id="example-init" class="chapter-explanation">
      <pre>
            {
                "#product-name": {
                    "Geekhub_Lesson5/js/example":{}
                }
            }
    </pre>
    <span><?php echo $block->escapeHtml(__('The * we used previously is actually a special case, for programs that don’t need to operate on DOM nodes'))?></span>
    <span><?php echo $block->escapeHtml(__('in this case the script will be bounded to an element which have the selector'))?></span>
</div>

<script type="text/x-magento-init">
    {
        "#example-init.chapter-explanation": {
            "Geekhub_Lesson5/js/example": {
                "config":
                    "<?= /* @escapeNotVerified */ 'Product has SKU '.$block->getProduct()->getSku(); ?>"
            }
        }
    }
</script>
